"""empty message

Revision ID: 1725a8dfbc5e
Revises: 94c9078fd05f
Create Date: 2025-04-08 13:28:59.943784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1725a8dfbc5e'
down_revision: Union[str, None] = '94c9078fd05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hosts', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('networks', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('networks', 'display_name')
    op.drop_column('hosts', 'display_name')
    op.drop_column('containers', 'display_name')
    # ### end Alembic commands ###
