"""empty message

Revision ID: 517e0d0cd97c
Revises: 1725a8dfbc5e
Create Date: 2025-04-08 15:22:40.165970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '517e0d0cd97c'
down_revision: Union[str, None] = '1725a8dfbc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networks', sa.Column('packets_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('networks', 'packets_number')
    # ### end Alembic commands ###
