"""empty message

Revision ID: 55552ac14bb0
Revises: 8520d1461510
Create Date: 2025-04-08 09:55:50.223223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '55552ac14bb0'
down_revision: Union[str, None] = '8520d1461510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('containers', 'packets_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('containers', 'packets_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
