"""empty message

Revision ID: abe522f7fbc3
Revises: 
Create Date: 2025-04-08 07:28:54.821201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'abe522f7fbc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('host_to_host',
    sa.Column('source_host_id', sa.Uuid(), nullable=False),
    sa.Column('target_host_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_host_id'], ['hosts.id'], ),
    sa.ForeignKeyConstraint(['target_host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('source_host_id', 'target_host_id')
    )
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('network_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'host_id')
    )
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('container_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_id', 'network_id')
    )
    op.create_table('network_to_network',
    sa.Column('source_network_id', sa.Integer(), nullable=False),
    sa.Column('target_network_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_network_id'], ['networks.id'], ),
    sa.ForeignKeyConstraint(['target_network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('source_network_id', 'target_network_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network_to_network')
    op.drop_table('containers')
    op.drop_table('networks')
    op.drop_table('host_to_host')
    op.drop_table('hosts')
    # ### end Alembic commands ###
