"""empty message

Revision ID: dd00a087d98b
Revises: 517e0d0cd97c
Create Date: 2025-04-08 20:54:31.721605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd00a087d98b'
down_revision: Union[str, None] = '517e0d0cd97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('network_to_network_target_network_id_fkey', 'network_to_network', type_='foreignkey')
    op.drop_constraint('network_to_network_source_network_id_fkey', 'network_to_network', type_='foreignkey')
    op.create_foreign_key(None, 'network_to_network', 'networks', ['target_network_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'network_to_network', 'networks', ['source_network_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'network_to_network', type_='foreignkey')
    op.drop_constraint(None, 'network_to_network', type_='foreignkey')
    op.create_foreign_key('network_to_network_source_network_id_fkey', 'network_to_network', 'networks', ['source_network_id'], ['id'])
    op.create_foreign_key('network_to_network_target_network_id_fkey', 'network_to_network', 'networks', ['target_network_id'], ['id'])
    # ### end Alembic commands ###
